name: Build

on:
  push:

jobs:
  build_app:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
#      - name: List files
#        run: ls
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          #cache: true

      - name: Build
        run: pwsh -ep bypass ./tools/publish.ps1
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./cipx/*.cipx
      
      - name: Upload APP to release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "./cipx/*.cipx"
          draft: true
          bodyFile: ./cipx/checksums.md
          token: ${{ secrets.GITHUB_TOKEN }}
